services:
  redis:
    image: redis:7.0-alpine
    container_name: wallet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      --save 60 1
      --requirepass your_redis_password 

volumes:
  redis_data: